# Generated by Django 6.0.2 on 2026-03-12 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('collection1')            
        """, """
            DELETE FROM store_collection
            WHERE title='collection1'
        """)
    ]
